#GNUPlot script
set term png
set output "huffman_encoderen.png"
set autoscale
set xlabel "MiB"
set ylabel "Tijd in seconden"
set title "Huffman encoderen"
set style line 1 lt 1 lw 2 pt 2 linecolor rgb "red"
set style line 2 lt 1 lw 2 pt 2 linecolor rgb "green"
set style line 3 lt 1 lw 2 pt 2 linecolor rgb "yellow"
set style line 4 lt 1 lw 2 pt 2 linecolor rgb "orange"
set style line 5 lt 1 lw 2 pt 2 linecolor rgb "blue"

plot "./blocksize1" using 1:2 with lines title "Blocksize 1", "./blocksize2" using 1:2 with lines title "Blocksize 2", "./blocksize3" using 1:2 with lines title "Blocksize 3", "./blocksize4" using 1:2 with lines title "Blocksize 4", "./blocksize5" using 1:2 with lines title "Blocksize 5"
